### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#1]
- [ ] Welcome email journey created for new subscribers - What do we want to direct people to in the first instance? @Theo to consider points and draft.
- [ ] Create SOP for Youtube Video Upload

**Comment by nathenf** [comment]
@theo-cox should we use this for small 1 action tasks, or do you prefer we just make notes on the project board? If the latter I propose we close this issue

**Comment by theo-cox** [comment]
@nathenf I think the latter. Given that, see below for indicator of how to close the issue.

**Comment by theo-cox** [comment]
WONTFIX. One of these done and one moved to #2
