### ISSUE TITLE
Finish editing for Web3 YouTube Video and upload

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#11]
The Web3 discussion is uploaded but private as it needs a title, thumbnail and (maybe) call to action to subscribe at the end. I've also made some improvements to the description but these may need reviewing and adding to (I haven't had time to watch the full thing to add timestamps, for eg) https://studio.youtube.com/video/bBP5cKAbAug/edit

## Acceptance

- [x] Video live 
- [x] Thumbnail added
- [x] Description finalised - Description is good
- [x] (?) Call to action added - I added cards and an end screen overlay

**Comment by nathenf** [comment]
I've also scheduled a post on Twitter about it

**Comment by nathenf** [comment]
Fixed - Youtube Video up
