### ISSUE TITLE
Priority YouTube Videos

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#14]
We have a few YouTube videos which I think we should prioritise to design in our new format, or do something else with.

The two with Roberto Unger from 2019 I think should be processed in our new style, as he's a big name thinker and the interview is our most viewed video.

The Gathering 2019 is just a really well shot video - unsure of what to do with it but it's worth having in our back pocket for content.

## Acceptance

- [x] Two Unger videos updated to our new style - All videos now optimized
- [x] Decison on what to do (if anything) with Gathering 2019 video **Leave this as your call @nathenf **

**Comment by nathenf** [comment]
@theo-cox the gathering 2019 video should be a promo video for Residencies in general. I think it should have a voiceover and then be placed on the main residencies web page. Thoughts?

**Comment by nathenf** [comment]
Fixed - All youtube videos now optimized!
