### ISSUE TITLE
Edit Residencies Page

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#42]
@EilidhRoss1 let's action this and move the residencies page around to prioritize upcoming residencies near the top of the page. 

##Acceptance

- [x] Residencies page is optimized to show current residencies at the top ✅ [**Done**](https://lifeitself.us/sympoiesis/)

##Tasks

- [x] @EilidhRoss1 can you make this change? ✅

**Comment by EilidhRoss1** [comment]
Can get on this today. I propose splitting the residencies into 'Upcoming Residencies' and 'Past Residencies', with upcoming at the top of the page and then past residencies being listed in reverse chronological order (most recent at the top).

**Comment by EilidhRoss1** [comment]
FIXED. Residencies page updated and optimized to show upcoming residencies at top of page

**Comment by EilidhRoss1** [comment]
FIXED. Residencies page updated and optimized to show upcoming residencies at top of page https://lifeitself.us/sympoiesis/
