### ISSUE TITLE
Website has email subscription forms including first name and email

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/comms#43]
**Job story:** when I am viewing great content on the LI site I want to easily be able to sign up for their newsletter (in a manner that safeguards against me forgetting to do so before I leave) so that I can be sure to keep up with what they're up to as an organisation in the future.

**Hypothesis:** Having our newsletter signup option present in this way will significantly increase the translation of site visitors to sign-ups. What we want to do is provide multiple touch points to raise awareness about our newsletter.

##Acceptance

- [ ] Email Subscription form available on every page

##Tasks

- [x] @khalilcodes to add subscription form to the website footer follow [this design](https://drive.google.com/file/d/16r1oAOoqjdNseeTajbAWVLvA6Acd8KvQ/view?usp=sharing)

**Comment by nathenf** [comment]
@rufuspollock this is same as #43 happy to merge them?

**Comment by rufuspollock** [comment]
@nathenf this *is* issue #43? So it would be merging to this issue? I specifically split this out from #2 which is a broader epic.

**Comment by nathenf** [comment]
Ah yes, I mean #2 apologies. Since we have defined the job story and hypothesis for both this issue and the larger task in #43 and this I feel is more of a subtask of the other issue.

**Comment by rufuspollock** [comment]
@nathenf this is a distinct subtask e.g. we can have signup on the lifeitself site without any "offer" etc (in fact that is the KISS solution) hence separating as distinct issue (plus found #2 getting a bit overwhelming for me and @khalilcodes as what was tech work). Happy for you to manage as you wish of course. ...

**Comment by nathenf** [comment]
@rufuspollock I've now updated both to make them more clear and defined

**Comment by khalilcodes** [comment]
@nathenf 
question from task above:

* *to add subscription form to the website footer*
      - There is a subscription form/Join our mailing list before the footer. Does this need to be removed since we are having it in the footer ? I think we had discussed this but sorry I forgot.

**Comment by nathenf** [comment]
@khalilcodes yes please

**Comment by nathenf** [comment]
Fixed - subscription form is now in the footer
