### ISSUE TITLE
January Newsletter

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#6]
## Acceptance

- [x] Newsletter sent out on 31st January

## Include

- [x] Berlin update
- [x] Sympoiesis 3 - we’ve got pics + Julie is writing a reflection blog (due today) + Video testimonials 
- [x] Advertising next residencies
- [x] Ecosystem mapping - Theo to Nag Rufus/Khalil to push update before next Monday
- [x] Blogs - we finished WPF last year, see blogs

**Comment by nathenf** [comment]
@theo-cox this is in draft, please review and make any suggestions for improvement or additions

**Comment by theo-cox** [comment]
Think this is good content list wise man - Julie's blog has been pushed to this Friday and ecosystem website should also be live by end of the week. Unsure if there's an actual draft for me to review then pls link it if so

**Comment by nathenf** [comment]
Hey I don't think I can link it to you, but the draft is in mailchimp under campaigns. I've added in a title for the community gathering so just add it what needs to go there.

**Comment by theo-cox** [comment]
@nathenf have reviewed and looks great - thanks so much! I've added a bit about the gathering and also made some minor edits, so take a look and then we're good to go

**Comment by theo-cox** [comment]
@nathenf one small flag. When we close issues that are complete it's good practice to add some info and then close with comment. In this case it would be something like:

FIXED. We sent this on 31 Jan 2022.
