### ISSUE TITLE
Changing slugs on posts, intentional?

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/comms#63]
Hi i just noticed that review of ken wilber integral spirituality slug had changed from 

https://lifeitself.us/2019/01/22/ken-wilber-integral-spirituality/

https://lifeitself.us/2019/01/22/wilber/

So i changed it back (former is more informative and mildly better for SEO) - hope that is ok.

Wondered if there was a reason for this or an accident (and if the latter how that is happening ... as a bit worrying).

**Comment by nathenf** [comment]
@rufuspollock we are going through the blogs finding evergreen content and optimizing for SEO and sharing. I agree the former slug is better for SEO

**Comment by rufuspollock** [comment]
@nathenf 👍

My 2c: slug correction on old points has dubious RoI (i.e. not worth it IMO) and it would be worth recording where we are doing it in case we break links at some point (e.g. at some point soon we may move off wordpress which may mean we lose redirection database -- i would have assumed it wasn't that important at this point ...)

**Comment by nathenf** [comment]
FIXED - Received and acted upon

**Comment by rufuspollock** [comment]
@nathenf can you confirm what was actual outcome i.e. have we stopped changing slugs? If we have changed slugs can we note them here (as per "recording where we are doing it" ...)
